### ISSUE TITLE
Escaping special characters in SELECT

### ISSUE THREAD

**Issue by chungwong** [dbohdan/sqawk#12]
I have a table of data where one of the column has a special character `#`
```
  #  Done Priority Get      Size  Name
  0: 100% Normal   Yes  709.3 MB  FILE_NAME
```
When I pipe it to `sqawk` it threw `unrecognized token: "#"` at me
```bash
sqawk -output json,indent=1 \
'select #,Done,Priority,Get,Size,Name from a' \
trim=left \
fields=1,2,3,4,5-end \
header=1
```
If I replace `#` to `ID`, then it is working perfectly.
I have tried to escape `#` with the following but none works
```
'select \#,Done,Priority,Get,Size,Name from a'
"select \#,Done,Priority,Get,Size,Name from a"
```

**Comment by dbohdan** [comment]
In SQLite's dialect of SQL you use double quotes to quote identifiers. For example,
```sh
sqawk -output json,indent=1 \
'select "#",Done,Priority,Get,Size,Name from a' ...
```
