### ISSUE TITLE
is there a limit of number of lines for input files?

### ISSUE THREAD

**Issue by alperyilmaz** [dbohdan/sqawk#16]
Hi,
I was testing the "summing up" example and noticed that `sqawk` gives I/O error for more than 10K lines. I was wondering if this is related to hardware limitations or software limitations? Is it possible to override this limit?
Also, I was surprised that it gives I/O error since I'm not reading any data from a file or writing results to a file. 

Here are the codes to reproduce:

10K lines
```bash
$ awk -v seed=$RANDOM 'BEGIN{srand(seed); split("ABCDEFGHIJKLMNOPQRSTUVWXYZ",chars,""); for (n=1;n<10000;n++){loc=int(rand()*26); num=int(rand()*10000);  print chars[loc+1]" "num }}'  | sqawk 'select a1, sum(a2) from a group by a1 order by a1'
A 1908044
B 2134362
C 1979623
D 1913669
E 1989040
F 1947681
G 1853303
...
```

100K lines
```bash
$ awk -v seed=$RANDOM 'BEGIN{srand(seed); split("ABCDEFGHIJKLMNOPQRSTUVWXYZ",chars,""); for (n=1;n<100000;n++){loc=int(rand()*26); num=int(rand()*10000);  print chars[loc+1]" "num }}'  | sqawk 'select a1, sum(a2) from a group by a1 order by a1'

error: disk I/O error
```

**Comment by alperyilmaz** [comment]
with `awk` there seems no problem. 10 million lines are processed in 6 seconds

```bash
$ time awk -v seed=$RANDOM 'BEGIN{srand(seed); split("ABCDEFGHIJKLMNOPQRSTUVWXYZ",chars,""); for (n=1;n<10000000;n++){loc=int(rand()*26); num=int(rand()*10000);  print chars[loc+1]" "num }}'  | awk '{s[$1] += $2} END {for (key in s) {print key, s[key] }}'
N 1916206699
A 1926008015
O 1920136864
B 1921829174
...

real	0m5.829s
user	0m9.264s
sys	0m0.072s
```

**Comment by dbohdan** [comment]
You have found a bug affecting Sqawk when it reads data ~~read~~ from the standard input (but, despite the error message, not when it reads data from disk).  Thanks for reporting it, and in detail!  9ca7455 should fix it.  Please tell me if it does.

**Comment by alperyilmaz** [comment]
Hi, I checked the latest commit, v.0.23.1, and it works fine. I even tested with 10 million lines and it works fine.
Thanks for the quick fix and thanks for the great tool..

**Comment by dbohdan** [comment]
> Hi, I checked the latest commit, v.0.23.1, and it works fine. I even tested with 10 million lines and it works fine.

:tada: 

> Thanks for the quick fix and thanks for the great tool..

I appreciate it!
