### ISSUE TITLE
Compiling assistance on freebsd

### ISSUE THREAD

**Issue by jungle-boogie** [dbohdan/sqawk#2]
Hello,

FreeBSD calls tclsh `tclsh8.6`, so when attempting to install your program, it can 't find tclsh. What file do I need to amend to have it find tclsh8.6?

Thanks!

**Comment by dbohdan** [comment]
Personally, what I do on FreeBSD when I have root is symlink
/usr/local/bin/tclsh to /usr/local/bin/tclsh8.6.

If you can't do that grep the repository for "#!/usr/bin/env tclsh" and
replace it with "#!/usr/bin/env tclsh8.6".

## 

Sent from my mobile device

**Comment by jungle-boogie** [comment]
Hello,

How do you handle the /usr/local/lib/tcl8.6? Even when sym linking lots tests fail with:
`---- errorInfo: couldn't load file "/usr/local/lib/tcl8.6/sqlite3/libtclsqlite3.so": Cannot open "/usr/local/lib/tcl8.6/sqlite3/libtclsqlite3.so"`

**Comment by dbohdan** [comment]
Have you installed the `tcl-sqlite3` port?

**Comment by jungle-boogie** [comment]
Hi,

Yes, tcl-sqlite3-3.8.10.2 is installed.

I compile sqlite3 from source but I don't know of any flags for sqlite3 to have this SO generated. 

I did generate a new sqlite3 binary with tcl:
`--with-tcl=/usr/local/lib/tcl8.6/ --enable-tcl`

If you're the maintainer, have you considered making a port of this program for freebsd? ;)

**Comment by dbohdan** [comment]
I'll look into it and try to write up installation notes for FreeBSD in the README before the end of the week.

If you want to run Sqawk right now build yourself a Tclkit with which to run it using the [KitCreator Web Interface](http://kitcreator.rkeene.org/kitcreator). Be sure to include SQLite and Tcllib. For help with KitCreator you can drop by #tcl on Freenode IRC.

> If you're the maintainer, have you considered making a port of this program for freebsd? ;)

I would but for a number of reasons I no longer use FreeBSD enough to justify maintaining a port. If you are up to it yourself you have my blessing. :-)

**Comment by jungle-boogie** [comment]
Hi,

Sure, I'll try making a package once I see the instructions to build successfully. Will you be making and marking releases?

Thanks for all your assistance!

**Comment by dbohdan** [comment]
I've [added to the README](https://github.com/dbohdan/sqawk/commit/a2c38cc09bd26b034a583201eb607fa1159310a0) what got Sqawk to work for me on a clean FreeBSD 10.2 installation. Tell me it works for you.

**Comment by jungle-boogie** [comment]
Hi @dbohdan,

That works and I've found the problem.

When compiling sqlite from src with just a plain `./configure` your make does not work:
https://gist.github.com/jungle-boogie/305c25100a62308e80fb

`./configure --disable-tcl` doesn't fix the problem with sqlite at compile time.

**Comment by dbohdan** [comment]
Great that hear that! I'm closing this issue now but you can comment here if you have any questions regarding packaging Sqawk for FreeBSD. For other things, please make a new issue.

**Comment by dbohdan** [comment]
P.S.: I'll tag the release tomorrow once I have fixed up the README a bit.

**Comment by dbohdan** [comment]
Tagged: https://github.com/dbohdan/sqawk/releases/tag/v0.10.0.

**Comment by jungle-boogie** [comment]
Nice work, thanks!

**Comment by dbohdan** [comment]
You're welcome!

**Comment by jungle-boogie** [comment]
Hello,

Future reference...

If you are installing sqlite from source, you need the libtclsqlite3.so for sqawk and it can be compiled in the following way in sqlite src:

`make tclsqlite3.c`
`gcc -fPIC -shared -I. -o libtclsqlite3.so tclsqlite3.c`

Or something like `gcc -fPIC -shared -I. -I/usr/local/include/tcl8.6 -o libtclsqlite3.so tclsqlite3.c`

I don't yet know the clang equivalent to this, though.
