### ISSUE TITLE
table print assistance

### ISSUE THREAD

**Issue by jungle-boogie** [dbohdan/sqawk#5]
Hello,

What do you expect with this `ls -l | sqawk -output table 'select a1 from a' trim=left`?

I would expect this to only select the first column. Instead, all rows are printed:

```
┌──────────┬──┬────┬────┬────┬───┬──┬─────┬─────────────────────┐
│   total  │23│    │    │    │   │  │     │                     │
├──────────┼──┼────┼────┼────┼───┼──┼─────┼─────────────────────┤
│drwxr-xr-x│ 7│sean│sean│  7 │Aug│31│01:59│         bin         │
├──────────┼──┼────┼────┼────┼───┼──┼─────┼─────────────────────┤
│-rw-r--r--│ 1│sean│sean│ 419│Aug│31│03:45│exp_1441043133748.csv│
├──────────┼──┼────┼────┼────┼───┼──┼─────┼─────────────────────┤
│drwxr-xr-x│ 5│root│sean│  5 │Aug│21│03:04│        perl5        │
├──────────┼──┼────┼────┼────┼───┼──┼─────┼─────────────────────┤
│-rw-r--r--│ 1│sean│sean│3892│Aug│28│03:14│      script.sh      │
├──────────┼──┼────┼────┼────┼───┼──┼─────┼─────────────────────┤
│-rw-r--r--│ 1│sean│sean│ 60 │Aug│20│07:54│ tmux-client-4279.log│
├──────────┼──┼────┼────┼────┼───┼──┼─────┼─────────────────────┤
│-rw-r--r--│ 1│sean│sean│9570│Aug│20│07:54│ tmux-server-4281.log│
└──────────┴──┴────┴────┴────┴───┴──┴─────┴─────────────────────┘
```

From you example, 'ps | sqawk -output table 'select a1 from a' trim=left' this also prints full data.

**Comment by dbohdan** [comment]
Sorry, but I cannot reproduce this. I get a single column in the output, e.g.,

```
┌───────────┐
│   total   │
├───────────┤
│-rw-rw-r--.│
├───────────┤
│-rw-rw-r--.│
├───────────┤
│-rw-rw-r--.│
├───────────┤
│drwxrwxr-x.│
├───────────┤
│drwxrwxr-x.│
├───────────┤
│-rw-r--r--.│
├───────────┤
│-rw-r--r--.│
├───────────┤
│-rw-rw-r--.│
├───────────┤
│-rw-rw-rw-.│
├───────────┤
│-rw-rw-r--.│
├───────────┤
│-rwxrwxr-x.│
├───────────┤
│-rw-rw-rw-.│
├───────────┤
│-rw-rw-rw-.│
├───────────┤
│-rw-rw-r--.│
├───────────┤
│-rw-rw-r--.│
├───────────┤
│-rw-rw-r--.│
├───────────┤
│-rw-rw-r--.│
├───────────┤
│drwxrwxr-x.│
└───────────┘
```

Could you post your `uname -a`, `sqawk -v` and `echo 'puts [info patchlevel]' | tclsh`?

**Comment by jungle-boogie** [comment]
Hello,

```
$ uname -a
Linux -debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux
```

`sqawk -v` doesn't seem to return anything.

```
$ echo 'puts [info patchlevel]' | tclsh
8.6.2
```

Also experienced on this:

```
~ % uname -a
FreeBSD tosh 11.0-CURRENT FreeBSD 11.0-CURRENT #0 r286893: Tue Aug 18 18:44:28 UTC 2015     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
```

`sqawk -v` doesn't return anything.

```
% echo 'puts [info patchlevel]' | tclsh
8.6.4
```

**Comment by dbohdan** [comment]
It's strange that you get no output from `sqawk -v`. What does `grep
version "$(which sqawk)"` say?

## 

Sent from my mobile device.

**Comment by jungle-boogie** [comment]
Hello,

```
$ grep version "$(which sqawk)"
variable version 0.13.1
variable version 0.3.0
    {v "Print version"}
# Report version.
    puts $::sqawk::version
```

And on the second machine:

```
% grep version "$(which sqawk)"
variable version 0.13.1
variable version 0.3.0
    {v "Print version"}
# Report version.
    puts $::sqawk::version
```

**Comment by dbohdan** [comment]
Looks like the issue requires further investigation. I will get back to you
once I have looked at it more closely.

## 

Sent from my mobile device.

**Comment by jungle-boogie** [comment]
Hi @dbohdan,

Let me know what else I can provide that may assist you.

**Comment by jungle-boogie** [comment]
Wow, that was a lot quicker than I was expecting!

How did it work for you initially and I had problems?

**Comment by dbohdan** [comment]
The problem had to do with the test at https://github.com/dbohdan/sqawk/commit/0c2a2a8313674c5c763c6b4a9cc3a85454ea3640#diff-00da39b724a1065eebaebcc31f66392bL154. The test worked when the script had the extension `.tcl`, which is how I tested it, but didn't when it was installed as `sqawk`. This meant that instead of Sqawk you ran a [standalone version of `tabulate.tcl`](http://wiki.tcl.tk/41682), which just so happens to work a lot like Sqawk with `output=table`. A funny thing, that. :-)

**Comment by jungle-boogie** [comment]
Oh, that's funny. 

 Thanks for writing sqawk and correcting the issues so quickly!

This also fixes `sqawk -v`, too.

**Comment by dbohdan** [comment]
You're welcome! I appreciate your bug reports.
