### ISSUE TITLE
truncating zeros

### ISSUE THREAD

**Issue by jungle-boogie** [dbohdan/sqawk#6]
Hello,

```
% cat test.csv
numbers,letters
001,a
002,b
003,c
004,d
5,e
6,f
7,g
8,i
9,j
10,j
```

When doing `cat test.csv| sqawk -output table 'select a1,a2 from a' trim=left format=csv2`, 001-004  turn into just 1,2,3,4. Actually all output options drop the 0 for 001-004.

If a trim option and format are not specified, then 001-004 are printed but its on one table.

Is there some work around to support numbers with 0 in front of numbers? If I add a decimal point in front of 001 and 002, sqawk will support this:
`% cat test.csv| sqawk -output json 'select a1,a2 from a' format=csvalt trim=none`

`[{"a1":"numbers","a2":"letters"},{"a1":"0.001","a2":"a"},{"a1":"0.002","a2":"b"},{"a1":"3","a2":"c"},{"a1":"4","a2":"d"},{"a1":"5","a2":"e"},{"a1":"6","a2":"f"},{"a1":"7","a2":"g"},{"a1":"8","a2":"i"},{"a1":"9","a2":"j"},{"a1":"10","a2":"j"}]`

I did json above because it's far easier to format that in the comment.

**Comment by dbohdan** [comment]
Thanks for bringing this issue to my attention.

I wrote a response [in the FAQ](https://github.com/dbohdan/sqawk/wiki/FAQ#sqawk-trims-leading-zeros-in-my-input-how-can-i-preserve-them). I may add functionality to set some columns' datatype to "text" later, which would preserve the input data in those columns as is.

**Comment by dbohdan** [comment]
I'll push a fix for this in v0.16.0.

**Comment by jungle-boogie** [comment]
```
% cat test.csv| sqawk 'select printf("%03d",a1),a2 from a'
000 
001 
002 
003 
004 
005 
006 
007 
008 
009 
010 
```

(no a2)

`cat test.csv | sqawk -output table 'select a1,a2 from a' datatypes=text` puts everything in one column. 

Are these expected?

**Comment by dbohdan** [comment]
Looks like you forgot `format=csv`.

**Comment by jungle-boogie** [comment]
`cat test.csv | sqawk -output table 'select a1,a2 from a' datatypes=text format=csv` correctly formats the table. My mistake for omitting the format option--thanks!

`cat test.csv | sqawk 'select printf("%03d",a1),a2 from a' format=csv`
drops header for numbers but keeps letters header.

**Comment by dbohdan** [comment]
You're welcome!

In the latter case, what happens is a little different than what you describe. Rather than **drop** the first item in the first column, `printf()` **converts** the text "numbers" to a zero and then formats it as `000`. This is correct behavior as far as SQLite is concerned. If you want to output the header you could do something like

```
sqawk 'select a1,a2 from a limit 1; select printf("%03d",a1),a2 from a limit -1 offset 1' format=csv test.csv
```

**Comment by jungle-boogie** [comment]
hi @dbohdan,

Thanks for the input and explanation, it works just great!

**Comment by dbohdan** [comment]
Once again, you're welcome!
